extends: airbnb
plugins:
  - react
  - jsx-a11y
  - import
parser: "babel-eslint"
env:
  browser: true
  node: true
  jest: true
rules:
  indent:
    - error
    - 4
  arrow-body-style:
    - 0
  react/jsx-indent:
    - error
    - 4
  react/jsx-indent-props:
    - error
    - 4
  react/jsx-filename-extension:
    - 1
    - extensions:
      - ".js"
      - ".jsx"